version: '3.8'

services:
    my-mysql:
        image: mysql
        ports:
            - '6121:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: Esy6927#
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
