version: '3.8'

services:
    my-mysql:
        image: mysql
        ports:
            - '6121:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: Esy6927#
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - mynetwork


volumes:
    mysql_data:

networks:
    mynetwork:
        driver: bridge
