version: 3.8

services:
    my-mysql:
        image: mysql:latest
        ports:
            - "6121:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: Esy6927#
        network:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
